baseURL: "https://ashiishkarhade.onrender.com"
languageCode: "en-us"
title: "Ashish Karhade"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Ashish Karhade"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Ashish Karhade" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Ashish."
    subtitle: "Backend Alchemist & DevOps Enthusiast 🧙‍♂️🔧"
    content: "A software engineer with a penchant for backend wizardry and a curious obsession with DevOps sorcery.  I weave code spells that power the web, leaving a trail of awestruck users and websites that dance merrily in the cloud."
    image: ./images/tn.png
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "https://www.icloud.com/iclouddrive/0c2zbATrfFWoNiXqqZY4Skdrg#Ashish%5FResume%5F2023"
      download: true
      newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/ashiishkarhade
        - icon: fab fa-github
          url: https://github.com/ashiishkarhade
        - icon: fab fa-twitter
          url: https://twitter.com/ashiishkarhade
      # customIcons:
      #   - icon: /fav.png
      #     url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "./images/me.png"
    content: |-
      I am a passionate Software Engineer with a relentless passion for crafting robust backend solutions, driving seamless DevOps practices, and delving into the fascinating world of Machine Learning and Artificial Intelligence. Welcome to my portfolio, where I showcase my journey of innovation and dedication in the realm of software development.

      I am currently working as Software Engineer at Credit Suisse, Pune INDIA.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Python"
        - "GO"
        - "Bash"
        - "JavaScript"
        - "Flask/Django"
        - "Gin, Mux"
        - "SQL - Postgres,MySQL"
        - "Docker"
        - "Kubernetes"
        - "Ansible"
        - "Gitlab CI"
        - "Terraform"
        - "Cloud - AWS,Azure"
        - "Linux/Unix"
        - "Machine Learning"
        - "Artificial Intelligence"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Software Developer"
        company: "Credit Suisse"
        companyUrl: "https://www.credit-suisse.com"
        date: "Aug 2021 - present"
        # featuredLink:
        #   enable: true
        #   name: "View the project"
        #   url: "https://example.com"
        content: "I am currently working as a software developer at [Credit Suisse](https://www.credit-suisse.com) in Pune, India. I am currently a Software Developer at Credit Suisse in Pune, India, I'm engaged in multiple exciting projects focused on crafting seamless CI/CD pipelines for diverse applications. My days are filled with tinkering with bash and Python scripts to ensure smooth pipeline operations. For Continuous Integration, we rely on the powerful GitLab CI, while Ansible takes the lead in orchestrating our efficient Continuous Deployment process. It's a tech adventure every day, and I love every bit of it! 🚀💻"

      - job: "Software Developer"
        company: "Raja Software Labs"
        companyUrl: "https://www.rajasoftwarelabs.com/history"
        date: "July 2021 - Aug 2021"
        content: "I had joined as a software developer at [RS Labs](https://www.rajasoftwarelabs.com/history) in Pune, India. I had completed an intensive 1-month web development training program. My learnt various things in EmberJS, JavaScript, and a range of web development functionalities, including REST APIs."

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Bachelor of Engineering in Computer Science"
        school:
          name: "Sinhgad Institute of Technology"
          url: "http://www.sinhgad.edu"
        date: "2017 - 2021"
        GPA: "8.5 out of 10.0"
        content: |-
          I Publiced one paper in the  Advances in Data Computing, Communication and Security Conference on AI.
          - [CNN for Detection of COVID-19 Using Chest X-Ray Images](https://link.springer.com/chapter/10.1007/978-981-16-8403-6_22)

          Extracurricular Activities
            - Leader @ Google Developer Students Club. 
            - Taught Machine Learning to 120+ students across various universities in Maharashtra. 
            - Received award for best event at Sinhgad Techfest, 2019. 
        # featuredLink:
        #   enable: true
        #   name: "My academic record"
        #   url: "https://example.com"
      - title: "High School"
        school:
          name: "Dr. Babasaheb Ambedkar College, Brahmapuri"
          url: "#"
        GPA: "8.0 out of 10.0"
        content: |-
          Studied Computer Science and Electronics.
        # featuredLink:
        #   enable: true
        #   url: "https://example.com"

  # Achievements
  achievements:
    enable: true
    title: "Certificates and Achievements"
    items:
      - title: Facilitator - Explore ML Program
        content: Selected for Explore ML Program at Google Office, Hyderabad & Bangalore
        url: https://events.withgoogle.com/explore-ml-in/
      - title: Google's Developer Student Club Lead
        content: Selected and Lead DSC Club at Sinhgad Institute of Technology, Pune. Conducted and taught on various events.
      - title: Tensorflow Developer Certified
        content: Cleared and received Tensorflow Certification from Google at first attempt.
        url: "https://github.com/gurusabarish/hugo-profile"
      - title: Microsoft Azure AZ-900 - Azure Fundamentals
        content: Cleared Microsoft Azure fundamentals at first attempt
      # - title: Google Summer of Code
      #   content: Contributed to a open source project.
      #   url: https://example.com

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: AudioVerse - Your Video-to-Audio Conversion Wizard
        content: A highly scalable Video-to-Audio Conversion Powered by Kubernetes and Microservices.
        image: /images/projects/profile.png
        featured:
          name: Source Code
          link: https://github.com/AshiishKarhade/Microservices-with-Kubernetes-and-Python
        badges:
          - "Python"
          - "Docker"
          - "Kubernetes"
          - "JWT"
          - "REST"
        links:
          - icon: fab fa-github
            url: https://github.com/AshiishKarhade/Microservices-with-Kubernetes-and-Python

      - title: GoChatNow :- Real time chat Made Effortless
        content: Connect, Chat, and Share Instantly with Real-time Websockets-Powered Conversations!
        image: /images/projects/converter.jpg
        featured:
          name: Source Code
          link: https://github.com/AshiishKarhade/Go-React-Chat-Application
        badges:
          - "GO"
          - "WebSockets"
          - "API"
          - "Gin"
        links:
          - icon: fab fa-github
            url: https://github.com/AshiishKarhade/Go-React-Chat-Application

      # - title: Hugo Profile V2
      #   content: A clean and simple Hugo template for personal portfolio and blog.
      #   image: /images/projects/profile2.jpg
      #   featured:
      #     name: Demo V2
      #     link: https://hugo-profile-2.netlify.app
      #   badges:
      #     - "Hugo"
      #     - "Bootstrap"
      #     - "Javascript"
      #   links:
      #     - icon: fab fa-github
      #       url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: akarhade5@gmail.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/ashiishkarhade
      linkedin: https://linkedin.com/in/ashiishkarhade
      twitter: https://twitter.com/ashiishkarhade
      instagram: https://instagram.com/ashiishkarhade
      facebook: https://facebook.com/ashiishkarhade

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"
